name: testing

on:
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup-node
        uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: testing
        run: |
          npm install
          npm test
